export interface OptimizationValue {
  target: number
  universalWeight: number
  weight: string | undefined
}

export interface Optimization {
  name: string
  values: OptimizationValue[]
}

const universal: Optimization = Object.freeze({
  name: 'Universal',
  values: [
    { target: 100, universalWeight: 0, weight: '000' },
    { target: 97.5, universalWeight: 25, weight: '025' },
    { target: 95, universalWeight: 50, weight: '050' },
    { target: 92.5, universalWeight: 75, weight: '075' },
    { target: 90, universalWeight: 100, weight: '100' },
    { target: 85, universalWeight: 150, weight: '150' },
    { target: 80, universalWeight: 200, weight: '200' },
    { target: 75, universalWeight: 250, weight: '250' },
    { target: 70, universalWeight: 300, weight: '300' },
    { target: 65, universalWeight: 350, weight: '350' },
    { target: 60, universalWeight: 400, weight: '400' },
    { target: 55, universalWeight: 450, weight: '450' },
    { target: 50, universalWeight: 500, weight: '500' },
    { target: 45, universalWeight: 550, weight: '550' },
    { target: 40, universalWeight: 600, weight: '600' },
    { target: 35, universalWeight: 650, weight: '650' },
    { target: 30, universalWeight: 700, weight: '700' },
    { target: 25, universalWeight: 750, weight: '750' },
    { target: 20, universalWeight: 800, weight: '800' },
    { target: 15, universalWeight: 850, weight: '850' },
    { target: 10, universalWeight: 900, weight: '900' },
    { target: 5, universalWeight: 950, weight: '950' },
    { target: 0, universalWeight: 999, weight: '999' },
  ],
})

const genome: Optimization = Object.freeze({
  name: 'Genome',
  values: [
    { target: 100, universalWeight: 0, weight: '000' },
    { target: 97.5, universalWeight: 25, weight: '015' },
    { target: 95, universalWeight: 50, weight: '025' },
    { target: 92.5, universalWeight: 75, weight: undefined },
    { target: 90, universalWeight: 100, weight: '050' },
    { target: 85, universalWeight: 150, weight: undefined },
    { target: 80, universalWeight: 200, weight: '075' },
    { target: 75, universalWeight: 250, weight: undefined },
    { target: 70, universalWeight: 300, weight: '085' },
    { target: 65, universalWeight: 350, weight: undefined },
    { target: 60, universalWeight: 400, weight: '100' },
    { target: 55, universalWeight: 450, weight: '200' },
    { target: 50, universalWeight: 500, weight: '300' },
    { target: 45, universalWeight: 550, weight: '400' },
    { target: 40, universalWeight: 600, weight: '500' },
    { target: 35, universalWeight: 650, weight: undefined },
    { target: 30, universalWeight: 700, weight: '600' },
    { target: 25, universalWeight: 750, weight: undefined },
    { target: 20, universalWeight: 800, weight: '700' },
    { target: 15, universalWeight: 850, weight: '800' },
    { target: 10, universalWeight: 900, weight: '900' },
    { target: 5, universalWeight: 950, weight: undefined },
    { target: 0, universalWeight: 999, weight: '950' },
  ],
})

const materialDesign: Optimization = Object.freeze({
  name: 'Material Design',
  values: [
    { target: 100, universalWeight: 0, weight: undefined },
    { target: 97.5, universalWeight: 25, weight: undefined },
    { target: 95, universalWeight: 50, weight: '50' },
    { target: 92.5, universalWeight: 75, weight: undefined },
    { target: 90, universalWeight: 100, weight: undefined },
    { target: 85, universalWeight: 150, weight: '100' },
    { target: 80, universalWeight: 200, weight: undefined },
    { target: 75, universalWeight: 250, weight: undefined },
    { target: 70, universalWeight: 300, weight: '200' },
    { target: 65, universalWeight: 350, weight: undefined },
    { target: 60, universalWeight: 400, weight: undefined },
    { target: 55, universalWeight: 450, weight: '300' },
    { target: 50, universalWeight: 500, weight: '400' },
    { target: 45, universalWeight: 550, weight: undefined },
    { target: 40, universalWeight: 600, weight: '500' },
    { target: 35, universalWeight: 650, weight: '600' },
    { target: 30, universalWeight: 700, weight: '700' },
    { target: 25, universalWeight: 750, weight: '800' },
    { target: 20, universalWeight: 800, weight: '900' },
    { target: 15, universalWeight: 850, weight: undefined },
    { target: 10, universalWeight: 900, weight: undefined },
    { target: 5, universalWeight: 950, weight: undefined },
    { target: 0, universalWeight: 999, weight: undefined },
  ],
})

const materialDesign3: Optimization = Object.freeze({
  name: 'Material Design (M3)',
  values: [
    { target: 100, universalWeight: 0, weight: '100' },
    { target: 97.5, universalWeight: 25, weight: '98' },
    { target: 95, universalWeight: 50, weight: '95' },
    { target: 92.5, universalWeight: 75, weight: undefined },
    { target: 90, universalWeight: 100, weight: '90' },
    { target: 85, universalWeight: 150, weight: undefined },
    { target: 80, universalWeight: 200, weight: '80' },
    { target: 75, universalWeight: 250, weight: undefined },
    { target: 70, universalWeight: 300, weight: '70' },
    { target: 65, universalWeight: 350, weight: undefined },
    { target: 60, universalWeight: 400, weight: '60' },
    { target: 55, universalWeight: 450, weight: undefined },
    { target: 50, universalWeight: 500, weight: '50' },
    { target: 45, universalWeight: 550, weight: undefined },
    { target: 40, universalWeight: 600, weight: '40' },
    { target: 35, universalWeight: 650, weight: '35' },
    { target: 30, universalWeight: 700, weight: '30' },
    { target: 25, universalWeight: 750, weight: '25' },
    { target: 20, universalWeight: 800, weight: '20' },
    { target: 15, universalWeight: 850, weight: '15' },
    { target: 10, universalWeight: 900, weight: '10' },
    { target: 5, universalWeight: 950, weight: '5' },
    { target: 0, universalWeight: 999, weight: '0' },
  ],
})

const adobeSpectrum: Optimization = Object.freeze({
  name: 'Adobe Spectrum',
  values: [
    { target: 100, universalWeight: 0, weight: undefined },
    { target: 97.5, universalWeight: 25, weight: undefined },
    { target: 95, universalWeight: 50, weight: '100' },
    { target: 92.5, universalWeight: 75, weight: undefined },
    { target: 90, universalWeight: 100, weight: '200' },
    { target: 85, universalWeight: 150, weight: '300' },
    { target: 80, universalWeight: 200, weight: '400' },
    { target: 75, universalWeight: 250, weight: '500' },
    { target: 70, universalWeight: 300, weight: undefined },
    { target: 65, universalWeight: 350, weight: '600' },
    { target: 60, universalWeight: 400, weight: '700' },
    { target: 55, universalWeight: 450, weight: undefined },
    { target: 50, universalWeight: 500, weight: '800' },
    { target: 45, universalWeight: 550, weight: '900' },
    { target: 40, universalWeight: 600, weight: undefined },
    { target: 35, universalWeight: 650, weight: '1000' },
    { target: 30, universalWeight: 700, weight: '1100' },
    { target: 25, universalWeight: 750, weight: '1200' },
    { target: 20, universalWeight: 800, weight: undefined },
    { target: 15, universalWeight: 850, weight: '1300' },
    { target: 10, universalWeight: 900, weight: undefined },
    { target: 5, universalWeight: 950, weight: undefined },
    { target: 0, universalWeight: 999, weight: undefined },
  ],
})

const ibmCarbon: Optimization = Object.freeze({
  name: 'IBM Carbon',
  values: [
    { target: 100, universalWeight: 0, weight: undefined },
    { target: 97.5, universalWeight: 25, weight: undefined },
    { target: 95, universalWeight: 50, weight: '10' },
    { target: 92.5, universalWeight: 75, weight: undefined },
    { target: 90, universalWeight: 100, weight: '20' },
    { target: 85, universalWeight: 150, weight: undefined },
    { target: 80, universalWeight: 200, weight: '30' },
    { target: 75, universalWeight: 250, weight: undefined },
    { target: 70, universalWeight: 300, weight: '40' },
    { target: 65, universalWeight: 350, weight: undefined },
    { target: 60, universalWeight: 400, weight: '50' },
    { target: 55, universalWeight: 450, weight: undefined },
    { target: 50, universalWeight: 500, weight: undefined },
    { target: 45, universalWeight: 550, weight: '60' },
    { target: 40, universalWeight: 600, weight: undefined },
    { target: 35, universalWeight: 650, weight: '70' },
    { target: 30, universalWeight: 700, weight: undefined },
    { target: 25, universalWeight: 750, weight: '80' },
    { target: 20, universalWeight: 800, weight: undefined },
    { target: 15, universalWeight: 850, weight: '90' },
    { target: 10, universalWeight: 900, weight: undefined },
    { target: 5, universalWeight: 950, weight: '100' },
    { target: 0, universalWeight: 999, weight: undefined },
  ],
})

const saleforceLightning: Optimization = Object.freeze({
  name: 'Saleforce Lightning',
  values: [
    { target: 100, universalWeight: 0, weight: undefined },
    { target: 97.5, universalWeight: 25, weight: undefined },
    { target: 95, universalWeight: 50, weight: '95' },
    { target: 92.5, universalWeight: 75, weight: undefined },
    { target: 90, universalWeight: 100, weight: '90' },
    { target: 85, universalWeight: 150, weight: undefined },
    { target: 80, universalWeight: 200, weight: '80' },
    { target: 75, universalWeight: 250, weight: undefined },
    { target: 70, universalWeight: 300, weight: '70' },
    { target: 65, universalWeight: 350, weight: undefined },
    { target: 60, universalWeight: 400, weight: '60' },
    { target: 55, universalWeight: 450, weight: undefined },
    { target: 50, universalWeight: 500, weight: '50' },
    { target: 45, universalWeight: 550, weight: undefined },
    { target: 40, universalWeight: 600, weight: '40' },
    { target: 35, universalWeight: 650, weight: undefined },
    { target: 30, universalWeight: 700, weight: '30' },
    { target: 25, universalWeight: 750, weight: undefined },
    { target: 20, universalWeight: 800, weight: '20' },
    { target: 15, universalWeight: 850, weight: '15' },
    { target: 10, universalWeight: 900, weight: '10' },
    { target: 5, universalWeight: 950, weight: undefined },
    { target: 0, universalWeight: 999, weight: undefined },
  ],
})

const antDesign: Optimization = Object.freeze({
  name: 'Ant Design',
  values: [
    { target: 100, universalWeight: 0, weight: undefined },
    { target: 97.5, universalWeight: 25, weight: undefined },
    { target: 95, universalWeight: 50, weight: '1' },
    { target: 92.5, universalWeight: 75, weight: undefined },
    { target: 90, universalWeight: 100, weight: '2' },
    { target: 85, universalWeight: 150, weight: undefined },
    { target: 80, universalWeight: 200, weight: '3' },
    { target: 75, universalWeight: 250, weight: '4' },
    { target: 70, universalWeight: 300, weight: undefined },
    { target: 65, universalWeight: 350, weight: '5' },
    { target: 60, universalWeight: 400, weight: '6' },
    { target: 55, universalWeight: 450, weight: undefined },
    { target: 50, universalWeight: 500, weight: undefined },
    { target: 45, universalWeight: 550, weight: '7' },
    { target: 40, universalWeight: 600, weight: undefined },
    { target: 35, universalWeight: 650, weight: '8' },
    { target: 30, universalWeight: 700, weight: undefined },
    { target: 25, universalWeight: 750, weight: '9' },
    { target: 20, universalWeight: 800, weight: '10' },
    { target: 15, universalWeight: 850, weight: undefined },
    { target: 10, universalWeight: 900, weight: undefined },
    { target: 5, universalWeight: 950, weight: undefined },
    { target: 0, universalWeight: 999, weight: undefined },
  ],
})

const accessiblePalette: Optimization = Object.freeze({
  name: 'Accessible Palette',
  values: [
    { target: 100, universalWeight: 0, weight: undefined },
    { target: 97.5, universalWeight: 25, weight: '50' },
    { target: 95, universalWeight: 50, weight: '100' },
    { target: 92.5, universalWeight: 75, weight: undefined },
    { target: 90, universalWeight: 100, weight: undefined },
    { target: 85, universalWeight: 150, weight: '200' },
    { target: 80, universalWeight: 200, weight: undefined },
    { target: 75, universalWeight: 250, weight: '300' },
    { target: 70, universalWeight: 300, weight: undefined },
    { target: 65, universalWeight: 350, weight: '400' },
    { target: 60, universalWeight: 400, weight: '500' },
    { target: 55, universalWeight: 450, weight: undefined },
    { target: 50, universalWeight: 500, weight: '600' },
    { target: 45, universalWeight: 550, weight: undefined },
    { target: 40, universalWeight: 600, weight: '700' },
    { target: 35, universalWeight: 650, weight: undefined },
    { target: 30, universalWeight: 700, weight: '800' },
    { target: 25, universalWeight: 750, weight: '900' },
    { target: 20, universalWeight: 800, weight: undefined },
    { target: 15, universalWeight: 850, weight: undefined },
    { target: 10, universalWeight: 900, weight: undefined },
    { target: 5, universalWeight: 950, weight: undefined },
    { target: 0, universalWeight: 999, weight: undefined },
  ],
})

const colorBox: Optimization = Object.freeze({
  name: 'ColorBox',
  values: [
    { target: 100, universalWeight: 0, weight: undefined },
    { target: 97.5, universalWeight: 25, weight: undefined },
    { target: 95, universalWeight: 50, weight: '0' },
    { target: 92.5, universalWeight: 75, weight: undefined },
    { target: 90, universalWeight: 100, weight: '0.5' },
    { target: 85, universalWeight: 150, weight: '1' },
    { target: 80, universalWeight: 200, weight: undefined },
    { target: 75, universalWeight: 250, weight: '1.5' },
    { target: 70, universalWeight: 300, weight: '2' },
    { target: 65, universalWeight: 350, weight: undefined },
    { target: 60, universalWeight: 400, weight: '3' },
    { target: 55, universalWeight: 450, weight: undefined },
    { target: 50, universalWeight: 500, weight: '4' },
    { target: 45, universalWeight: 550, weight: undefined },
    { target: 40, universalWeight: 600, weight: '5' },
    { target: 35, universalWeight: 650, weight: '6' },
    { target: 30, universalWeight: 700, weight: '7' },
    { target: 25, universalWeight: 750, weight: undefined },
    { target: 20, universalWeight: 800, weight: '8' },
    { target: 15, universalWeight: 850, weight: undefined },
    { target: 10, universalWeight: 900, weight: '9' },
    { target: 5, universalWeight: 950, weight: undefined },
    { target: 0, universalWeight: 999, weight: '10' },
  ],
})

export const optimizations: Optimization[] = [
  universal,
  genome,
  materialDesign,
  materialDesign3,
  adobeSpectrum,
  ibmCarbon,
  saleforceLightning,
  antDesign,
  accessiblePalette,
  colorBox,
]
